contact_links:
  - name: You have a question about the Telegram API or how to do something with WTelegramClient?
    url: https://stackoverflow.com/questions/ask?tags=c%23+wtelegramclient+telegram-api
    about: The answer to your question can be helpful to the community so it's better to ask them on StackOverflow --->
